name: 🐞 Bug Report
description: Report a bug to help us improve the project
title: "[Bug]: "
labels: [bug]
assignees:
  - your-github-username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
      placeholder: A clear and concise description of the problem...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or screenshots
      description: Please copy and paste any relevant console output or error logs.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Ubuntu
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App or script version
      placeholder: ex. v1.2.3

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
